version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/couphone
    overwrite: yes
permissions:
  - object: /home/ubuntu/couphone/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall: # CodeDeploy의 AfterInstall 단계에서 실행
    - location: scripts/stop.sh # hooks에서 실행할 스크립트의 위치
      timeout: 60 # 스크립트 실행에 허용되는 최대 시간, 넘으면 배포 실패
      runas: ubuntu # 스크립트를 실행하는 사용자
  ApplicationStart: # CodeDeploy의 ApplicationStart 단계에서 실행
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu