# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "feature/member" ]
  pull_request:
    branches: [ "feature/member" ]

permissions:
  write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: write CLOUDFRONT_DOMAIN at Main
        run: echo "CLOUDFRONT_DOMAIN=${{secrets.CLOUDFRONT_DOMAIN}}" >> application.yml
        working-directory: ./src/main/resources

      - name: write DATASOURCE_PASSWORD_DEV at Main
        run: echo "DATASOURCE_PASSWORD_DEV=${{secrets.DATASOURCE_PASSWORD_DEV}}" >> application.yml
        working-directory: ./src/main/resources

      - name: write DATASOURCE_URL_DEV at Main
        run: echo "DATASOURCE_URL_DEV=${{secrets.DATASOURCE_URL_DEV}}" >> application.yml
        working-directory: ./src/main/resources

      - name: write DATASOURCE_USERNAME_DEV at Main
        run: echo "DATASOURCE_USERNAME_DEV=${{secrets.DATASOURCE_USERNAME_DEV}}" >> application.yml
        working-directory: ./src/main/resources

      - name: write S3_ACCESS_KEY at Main
        run: echo "S3_ACCESS_KEY=${{secrets.S3_ACCESS_KEY}}" >> application.yml
        working-directory: ./src/main/resources

      - name: write S3_SECRET_KEY at Main
        run: echo "S3_SECRET_KEY=${{secrets.S3_SECRET_KEY}}" >> application.yml
        working-directory: ./src/main/resources

      - name: write JWT_SECRET_KEY at Main
        run: echo "JWT_SECRET_KEY=${{secrets.JWT_SECRET_KEY}}" >> application.yml
        working-directory: ./src/main/resources

      - name: write JWT_EXPIRED_IN at Main
        run: echo "JWT_EXPIRED_IN=${{secrets.JWT_EXPIRED_IN}}" >> application.yml
        working-directory: ./src/main/resources

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          host port: 3306
          character set server: 'utf8'
          mysql database: 'couphone-database'
          mysql user: ${{secrets.DATASOURCE_USERNAME_DEV}}
          mysql password: ${{secrets.DATASOURCE_PASSWORD_DEV}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

